### PR TITLE
add fbi 2 persons, trap 6 persons

### PR DESCRIPTION
**Pull request by sirawit-suk**
Adding 8 persons.
fbi: denji, makima (2 persons)
trap: akira, hatsuka, ruka, mayuri, mahiru, chitose (6 persons)

I write "en" name as romaji form (surname-name) and place a "space" between surname and name

Nice Repo! Love it ❤. The man of culture. 😉
I spent almost 20 mins to completed that captcha 🤣

### CODE REVIEW

**Review by leomotors — APPROVED** [review]
I thought I added Ruka to the list. How I forgot this. 🤔

**Comment by sirawit-suk** [comment]
One more thing, I think sakurajima Mai is not an adult one. By the way, it's up to you if you wanna change it or not. 😄

**Comment by leomotors** [comment]
> One more thing, I think sakurajima Mai is not an adult one. By the way, it's up to you if you wanna change it or not. 😄

The problem we can't solve yet. Is she adult?

image

**Comment by sirawit-suk** [comment]
In my perspective, adult is the end of school life or university. but 17-18 can call it young adult too.
pone 0215637 g001

**Pull request merged**
